(autoload 'php-mode-version                     "php-mode" "" t)
(autoload 'php-beginning-of-defun               "php-mode" "" t)
(autoload 'php-end-of-defun                     "php-mode" "" t)
(autoload 'php-check-html-for-indentation       "php-mode" "" nil)
(autoload 'php-cautious-indent-region           "php-mode" "" nil)
(autoload 'php-cautious-indent-line             "php-mode" "" nil)
(autoload 'php-mode                             "php-mode" "" t)
(autoload 'php-complete-function                "php-mode" "" t)
(autoload 'php-completion-table                 "php-mode" "" nil)
(autoload 'php-build-table-from-file            "php-mode" "" nil)
(autoload 'php-build-table-from-path            "php-mode" "" nil)
(autoload 'php-get-pattern                      "php-mode" "" nil)
(autoload 'php-show-arglist                     "php-mode" "" t)
(autoload 'php-search-documentation             "php-mode" "" t)
(autoload 'php-browse-manual                    "php-mode" "" t)
(provide 'php-mode-epackage-autoloads)
